[package]
name = "dsl_main"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dsl_runtime ={ path = "../dsl_runtime"}
dsl_macro ={ path = "../dsl_macro"}